export const copy = {
  appTitle: "Tin nhắn",
  loginTitle: "Đăng nhập",
  passwordLabel: "Mật khẩu",
  loginButton: "Đăng nhập",
  loginHint: "Mật khẩu máy chủ cục bộ",
  qrTitle: "Kết nối Zalo",
  qrHint: "Mở ứng dụng Zalo trên điện thoại thật và quét mã này.",
  qrMissing: "Đang tạo mã QR...",
  qrLabel: "Mã QR đăng nhập Zalo",
  emptyChats: "Chưa có cuộc trò chuyện",
  loadError: "Không tải được dữ liệu",
  composerLabel: "Nhập tin nhắn",
  sendLabel: "Gửi",
  aiLabel: "AI",
  aiSwitch: "Bật tắt AI",
  aiPending: "AI đang trả lời...",
  sendFailed: "Gửi thất bại",
  loading: "Đang tải",
  logout: "Đăng xuất",
  logoutTitle: "Đăng xuất Zalo",
  logoutHint: "Phiên hiện tại sẽ đóng. Quét mã QR để đăng nhập lại.",
  cancel: "Hủy",
} as const;
