export const copy = {
  appTitle: "Tin nhắn",
  loginTitle: "Đăng nhập",
  passwordLabel: "Mật khẩu",
  loginButton: "Đăng nhập",
  loginHint: "Mật khẩu máy chủ cục bộ",
  qrTitle: "Kết nối Zalo",
  qrHint: "Mở ứng dụng Zalo trên điện thoại thật và quét mã này.",
  qrMissing: "Đang tạo mã QR...",
  qrLabel: "Mã QR đăng nhập Zalo",
  emptyChats: "Chưa có cuộc trò chuyện",
  loadError: "Không tải được dữ liệu",
  channelZalo: "Zalo",
  channelFacebook: "Facebook",
  zaloOffline: "Zalo chưa kết nối",
  zaloConnect: "Kết nối",
  composerLabel: "Nhập tin nhắn",
  sendLabel: "Gửi",
  aiLabel: "AI",
  aiSwitch: "Bật tắt AI",
  aiAllLabel: "Tất cả",
  aiAllSwitch: "Bật AI tất cả",
  clearContext: "Xóa ngữ cảnh",
  clearContextTitle: "Xóa ngữ cảnh",
  clearContextHint: "Tin nhắn và trí nhớ của cuộc chat này sẽ mất. Hồ sơ khách và booking đã lưu vẫn giữ.",
  deleteChatTitle: "Xóa cuộc trò chuyện",
  deleteChatHint: "Cuộc trò chuyện sẽ biến khỏi danh sách. Booking đã lưu vẫn giữ.",
  aiPending: "AI đang trả lời...",
  sendFailed: "Gửi thất bại",
  loading: "Đang tải",
  logout: "Đăng xuất",
  logoutTitle: "Đăng xuất Zalo",
  logoutHint: "Phiên hiện tại sẽ đóng. Quét mã QR để đăng nhập lại.",
  cancel: "Hủy",
  manage: "Quản lý",
  back: "Quay lại",
  manageTitle: "Quản lý",
  manageShop: "Knowledge quán",
  manageStaff: "Nhân viên",
  manageCustomers: "Khách hàng",
  manageBookings: "Booking",
  manageSessions: "Phiên chat",
  saved: "Đã lưu.",
  save: "Lưu",
  remove: "Xóa",
  add: "Thêm",
  emptyList: "Chưa có dữ liệu.",
  shopName: "Tên quán",
  tagline: "Khẩu hiệu",
  address: "Địa chỉ",
  directions: "Chỉ đường",
  hotline: "Hotline",
  intro: "Giới thiệu",
  amenities: "Tiện nghi",
  policyBooking: "Đặt lịch",
  policyCancel: "Hủy lịch",
  policyLate: "Đến muộn",
  policyNewGuest: "Khách mới",
  voice: "Giọng bot",
  forbidden: "Điều cấm",
  hours: "Giờ mở cửa",
  services: "Dịch vụ",
  serviceName: "Tên dịch vụ",
  duration: "Số phút",
  price: "Giá (đồng)",
  description: "Mô tả",
  addService: "Thêm dịch vụ",
  staffName: "Tên",
  gender: "Giới tính",
  genderNam: "Nam",
  genderNu: "Nữ",
  genderKhac: "Khác",
  specialties: "Chuyên môn",
  years: "Số năm",
  bio: "Giới thiệu",
  accepting: "Đang nhận khách",
  shifts: "Lịch làm",
  shiftStart: "Bắt đầu",
  shiftEnd: "Kết thúc",
  shiftInvalid: "Mỗi ca cần đủ giờ bắt đầu và kết thúc, dạng HH:MM.",
  addStaff: "Thêm nhân viên",
  photo: "Ảnh nhân viên",
  pickPhoto: "Chọn ảnh",
  photoLater: "Lưu nhân viên trước khi thêm ảnh.",
  photoDenied: "Chưa được phép mở thư viện ảnh.",
  displayName: "Tên hiển thị",
  customerName: "Tên khách",
  phone: "Số điện thoại",
  notes: "Ghi chú",
  zaloName: "Tên Zalo",
  facts: "Bot đã ghi",
  summary: "Tóm tắt",
  noFacts: "Chưa ghi nhận.",
  noSummary: "Chưa có tóm tắt.",
  orders: "Lịch sử đơn",
  noOrders: "Chưa có đơn.",
  sessionButton: "Phiên",
  sessionTitle: "Phiên chat",
  stageChaoHoi: "Chào hỏi",
  stageTuVan: "Tư vấn",
  stageLenDon: "Lên đơn booking",
  stageChoXacNhan: "Đợi nhân viên xác nhận",
  stageChot: "Chốt",
  bookingWhen: "Giờ",
  bookingStaff: "Nhân viên",
  staffUnset: "Chưa chọn",
  confirmBooking: "Chốt",
  rejectBooking: "Từ chối",
  completeBooking: "Hoàn thành",
  cancelBooking: "Hủy đơn",
  saveWhen: "Lưu giờ",
  emptyBookings: "Chưa có đơn. Bot tạo đơn khi khách nói đủ gói, giờ và tên hoặc số điện thoại.",
  numberInvalid: "Số phút, giá hoặc số năm không hợp lệ.",
} as const;
